[package]
authors = ["Yann Ramin <yann@theatr.us>"]
edition = "2018"
name = "algo"
publish = false
version = "0.1.0"

[dependencies]
num-traits = { version = "0", default-features = false, features = ["libm"] }

[dev-dependencies]
anyhow = "1"
approx = "0"
